spring:
  application:
    name: appleplayground
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:appleplayground}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# AWS S3 설정
aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION:ap-northeast-2}

logging:
  level:
    com.apple.appleplayground: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    software.amazon.awssdk: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    doc-expansion: none
    filter: true
    disable-swagger-default-url: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  group-configs:
    - group: auth
      display-name: "인증 API"
      paths-to-match: "/api/auth/**"
    - group: follow
      display-name: "팔로우 API"
      paths-to-match: "/api/follow/**"
    - group: blog
      display-name: "블로그 API"
      paths-to-match: "/api/blog/**"
    - group: image
      display-name: "이미지 API"
      paths-to-match: "/api/images/**"
    - group: public
      display-name: "공개 API"
      paths-to-match: "/api/public/**"